# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Experiment
        run: |
          docker run `
          -p 8081:8081 `
          -p 8901:8901 `
          -p 8902:8902 `
          -p 8903:8903 `
          -p 10250:10250 `
          -p 10251:10251 `
          -p 10252:10252 `
          -p 10253:10253 `
          -p 10254:10254 `
          -p 10255:10255 `
          -p 10350:10350 `
          --detach `
          --memory 3g --cpus=2.0 `
          --name=test-linux-emulator `
          -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3 -it `
          mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
          Write-Host "Waiting"
          Start-Sleep -Seconds 60
          docker logs test-linux-emulator
          Write-Host "Testing"
        shell: pwsh
