# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Experiment
        run: |
          IP_ADDRESS=$(hostname -I | awk '{print $1}')
          echo $IP_ADDRESS
          docker run `
          --publish 8081:8081 `
          --detach `
          --memory 3g --cpus=2.0 `
          --name=test-linux-emulator `
          --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1 `
          --env AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false `
          --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE= $IP_ADDRESS`
          --tty `
          mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
          Write-Host "Waiting"
          Start-Sleep -Seconds 60
          docker logs test-linux-emulator
          curl -k "https://$IP_ADDRESS/_explorer/emulator.pem" > emulator.pem
          keytool -importcert -keystore cacerts -alias emulator_cert -file "emulator.pem" -storepass "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==" -noprompt -trustcacerts
          Invoke-WebRequest  -UseBasicParsing -Uri https://IP_ADDRESS:8081/_explorer/index.html
        shell: pwsh
