name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  container-test-job-tty:
    runs-on: ubuntu-latest

    steps:
      - name: Print Machine Information
        run: |
          lscpu
          free -h
          df -h
          uname -a

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Azure Cosmos DB Emulator with TTY
        run: |
          docker run \
          --publish 8081:8081 \
          --detach \
          --memory 3g --cpus=2.0 \
          --name=test-linux-emulator-tty \
          --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 \
          --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 \
          --tty \
          mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest

      - name: Wait for Emulator to Start
        run: sleep 60

      - name: Get Emulator Logs
        run: docker logs test-linux-emulator-tty

      - name: Check Emulator Logs for 'Started' Keyword
        run: |
          if docker logs test-linux-emulator-tty | grep -q "Started"; then
            echo "Emulator started successfully."
          else
            echo "Emulator failed to start." >&2
            exit 1
          fi

      - name: Test Emulator Endpoint
        run: curl -k "https://127.0.0.1:8081/_explorer/index.html"

      - name: Cleanup
        run: docker rm -f test-linux-emulator-tty

  container-test-job-no-tty:
    runs-on: ubuntu-latest

    steps:
      - name: Print Machine Information
        run: |
          lscpu
          free -h
          df -h
          uname -a

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Azure Cosmos DB Emulator without TTY
        run: |
          docker run \
          --publish 8081:8081 \
          --detach \
          --memory 3g --cpus=2.0 \
          --name=test-linux-emulator-no-tty \
          --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 \
          --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 \
          mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest

      - name: Wait for Emulator to Start
        run: sleep 60

      - name: Get Emulator Logs
        run: docker logs test-linux-emulator-no-tty

      - name: Check Emulator Logs for 'Started' Keyword
        run: |
          if docker logs test-linux-emulator-no-tty | grep -q "Started"; then
            echo "Emulator started successfully."
          else
            echo "Emulator failed to start." >&2
            exit 1
          fi

      - name: Test Emulator Endpoint
        run: curl -k "https://127.0.0.1:8081/_explorer/index.html"

      - name: Cleanup
        run: docker rm -f test-linux-emulator-no-tty
