name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  container-test-job-tty:
    runs-on: ubuntu-latest

    steps:
      - name: Print Machine Information
        run: |
          lscpu
          free -h
          df -h
          uname -a

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run and Test Emulator with TTY
        run: |
          for i in {1..3}; do
            echo "Run #$i"

            docker run \
              --publish 8081:8081 \
              --detach \
              --memory 3g --cpus=2.0 \
              --name=test-linux-emulator-tty-$i \
              --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 \
              --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 \
              --tty \
              mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest

            echo "Waiting for Emulator to Start"
            sleep 60

            echo "Getting Emulator Logs"
            docker logs test-linux-emulator-tty-$i

            echo "Checking Emulator Logs for 'Started' Keyword"
            if docker logs test-linux-emulator-tty-$i | grep -q "Started"; then
              echo "Emulator started successfully."
            else
              echo "Emulator failed to start." >&2
              exit 1
            fi

            echo "Testing Emulator Endpoint"
            curl -k "https://127.0.0.1:8081/_explorer/index.html"

            echo "Cleaning up"
            docker rm -f test-linux-emulator-tty-$i
          done

  container-test-job-no-tty:
    runs-on: ubuntu-latest

    steps:
      - name: Print Machine Information
        run: |
          lscpu
          free -h
          df -h
          uname -a

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run and Test Emulator without TTY
        run: |
          for i in {1..3}; do
            echo "Run #$i"

            docker run \
              --publish 8081:8081 \
              --detach \
              --memory 3g --cpus=2.0 \
              --name=test-linux-emulator-no-tty-$i \
              --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 \
              --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 \
              mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest

            echo "Waiting for Emulator to Start"
            sleep 60

            echo "Getting Emulator Logs"
            docker logs test-linux-emulator-no-tty-$i

            echo "Checking Emulator Logs for 'Started' Keyword"
            if docker logs test-linux-emulator-no-tty-$i | grep -q "Started"; then
              echo "Emulator started successfully."
            else
              echo "Emulator failed to start." >&2
              exit 1
            fi

            echo "Testing Emulator Endpoint"
            curl -k "https://127.0.0.1:8081/_explorer/index.html"

            echo "Cleaning up"
            docker rm -f test-linux-emulator-no-tty-$i
          done
