name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  container-test-job-tty:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Azure Cosmos DB Emulator with TTY
        run: |
          docker run \
          --publish 8081:8081 \
          --detach \
          --memory 3g --cpus=2.0 \
          --name=test-linux-emulator-tty \
          --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1 \
          --env AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false \
          --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 \
          --tty \
          mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator

      - name: Wait for Emulator to Start
        run: sleep 60

      - name: Get Emulator Logs
        run: docker logs test-linux-emulator-tty

      - name: Test Emulator Endpoint
        run: curl -k "https://127.0.0.1:8081/_explorer/index.html"

  container-test-job-no-tty:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Azure Cosmos DB Emulator without TTY
        run: |
          docker run \
          --publish 8081:8081 \
          --detach \
          --memory 3g --cpus=2.0 \
          --name=test-linux-emulator-no-tty \
          --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1 \
          --env AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false \
          --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 \
          mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator

      - name: Wait for Emulator to Start
        run: sleep 60

      - name: Get Emulator Logs
        run: docker logs test-linux-emulator-no-tty

      - name: Test Emulator Endpoint
        run: curl -k "https://127.0.0.1:8081/_explorer/index.html"
