name: Setup Cosmos DB Emulator on Windows

on:
  push:
    branches:
      - main

jobs:
  cosmosdb-emulator:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download and Install Cosmos DB Emulator
      run: |
        # Download Cosmos DB Emulator MSI
        Invoke-WebRequest -Uri https://aka.ms/cosmosdb-emulator -OutFile cosmosdb-emulator-installer.msi
        
        # Install the Cosmos DB Emulator using msiexec
        Start-Process msiexec.exe -ArgumentList '/i', 'cosmosdb-emulator-installer.msi', '/quiet', '/norestart' -Wait

    - name: Start Cosmos DB Emulator and Measure Time
      run: |
        # Define the correct path to the Cosmos DB Emulator executable
        $emulatorPath = "C:\Program Files\Azure Cosmos DB Emulator\CosmosDB.Emulator.exe"

        # Check if the emulator executable exists at the given path
        if (Test-Path $emulatorPath) {
          $startTime = Get-Date
          Write-Host "Starting Cosmos DB Emulator..."
          Start-Process -Wait -FilePath $emulatorPath

          # Wait for emulator to start (if necessary, based on your logic)
          $endTime = Get-Date
          $duration = $endTime - $startTime
          Write-Host "Cosmos DB Emulator started in $($duration.TotalSeconds) seconds"
        } else {
          Write-Host "Cosmos DB Emulator executable not found at path $emulatorPath"
        }
